### ISSUE TITLE
I can't sync after I edit some block

### ISSUE THREAD

**Issue by Batapha** [m1guelpf/roam-app#3]
I have to say this app is amazing for me which I have waiting for a long time.

But when I use the app, after I edit some block, I can't sync. Even I can open pwa version.

iOS  15 
iPhone 7 Plus 

![](https://raw.githubusercontent.com/Batapha/RoamImage/main/2021/1628514376619.png)

Picture shows 'Roam is online'.

Only when I reopen RR, sync will work will.

Thank you for making such an amazing app!

**Comment by m1guelpf** [comment]
@Batapha If this is something that also happens from Safari (or on the PWA mode), I, unfortunately, can't do anything about it, and you should contact the Roam folks to report it 😃
